version: '3'

services:
  cloudflare-hosts-updater:
    build: .
    container_name: cloudflare-hosts-updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    ports:
      - "18080:8080"